# Generated by Django 5.0.7 on 2024-07-12 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='desription',
            new_name='description',
        ),
    ]
